sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index, name="indexpage"),
    path('student/', include('studentmanagement.urls')),
    path('teacher/', include('teachermanagement.urls')),
    path('superadmin/', include('superadminmanagement.urls')),
    path('auth/', include('authentications.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superadminmanagement/urls.py
from django.urls import path 
from . import views


app_name = 'superadmin'

urlpatterns = [
    path('', views.Dashboard, name="admindashboard"),
    path('booklist/', views.Booklist.as_view(), name="booklist"),
    path('addbook/', views.AddBook.as_view(), name="addbook"),
    path('<pk>/updatebook', views.UpdateBook.as_view(), name="updatebook"),
    path('<pk>/delete/', views.DeleteBook.as_view(), name="deletebook"),
    path('addstudent/', views.AddStudent.as_view(), name="addstudent"),
    path('students/', views.AllStudent.as_view(), name="allstudent"),
    path('studentdetail/<pk>', views.StudentDetail.as_view(), name="studentdetail"),
    path('createnotice/', views.CreateNotice.as_view(), name="createnotice"),
    path('noticelist/', views.ListNotice, name="noticelist"),
    path('readnotice/<pk>', views.ReadNotice.as_view(), name="readnotice"),
    path('updatenotice/<pk>', views.UpdateNotice.as_view(), name="updatenotice"),
    path('deletenotice/<pk>', views.DeleteNotice.as_view(), name="deletenotice"),
]

superadminmanagement/models.py
from django.db import models
import random
import datetime
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget

currentdatetime = datetime.datetime.now()

generate_id = currentdatetime.strftime("%f")



# Generating Random Number
random_number = random.randint(5, 9999)

# Students Information
class StudentInfo(models.Model):
    student_id = models.CharField(max_length=10, default="MGSD"+generate_id,  unique=True, verbose_name="Student ID -Genereated")
    firstname = models.CharField(max_length=20, verbose_name="First Name")
    lastname = models.CharField(max_length=20, verbose_name="Last Name")
    fathername = models.CharField(max_length=20, verbose_name="Father's Name")
    mothername = models.CharField(max_length=20, verbose_name="Mother's Name")
    address = models.TextField(default="", verbose_name="Permanent Address")
    guardian_phone = models.CharField(max_length=20, verbose_name="Guardian Phone Number")
    student_phone = models.CharField(max_length=20, verbose_name="Student Phone Number")
    student_email = models.EmailField(max_length=40, verbose_name="Email Address (If any)", blank=True)
    profile_image = models.ImageField(upload_to="students/", null=True, blank=True)

    def __str__(self):
        return self.student_id+" "+self.firstname
    

# Teachers Information
class TeacherInfo(models.Model):
    teacher_id = models.CharField(max_length=8, default="TCHR"+str(random_number), verbose_name="Teacher ID (Generated)", unique=True)
    firstname = models.CharField(max_length=20, verbose_name="First Name")
    lastname = models.CharField(max_length=20, verbose_name="Last Name")
    teacher_of_subject = models.CharField(max_length=30, verbose_name="Dedicated Subject")
    last_graduated_degree = models.CharField(max_length=30, verbose_name="Last Graduation Degree")
    last_graduated_subject = models.CharField(max_length=30, verbose_name="Subject of Graduation")
    last_graduated_university = models.CharField(max_length=30, verbose_name="Graduated from University")
    last_graduated_session = models.CharField(max_length=30, verbose_name="Session")
    address = models.TextField(default="", verbose_name="Permanent Address")
    teacher_phone = models.CharField(max_length=20, verbose_name="Phone Number")
    teacher_email = models.EmailField(max_length=40, verbose_name="Email Address")
    profile_image = models.ImageField(upload_to="teachers/", null=True, blank=True)

    def __str__(self):
        return self.firstname+" - "+self.teacher_of_subject



# Staff Information
class StaffInfo(models.Model):
    staff_id = models.CharField(max_length=8, default="STFF"+str(random_number), verbose_name="Staff ID (Generated)", unique=True)
    staff_firstname = models.CharField(max_length=20, verbose_name="First Name")
    staff_lastname = models.CharField(max_length=20, verbose_name="Last Name")
    edu_qualification = models.CharField(max_length=30, verbose_name="Educational Qualification" ,null=True)
    staff_job_department = models.CharField(max_length=30, verbose_name="Staff Department")
    address = models.TextField(default="", verbose_name="Permanent Address")
    staff_phone = models.CharField(max_length=20, verbose_name="Phone Number")
    staff_email = models.EmailField(max_length=40, blank=True, verbose_name="Email Address")
    staff_image = models.ImageField(upload_to="staffs/", null=True, blank=True)
    

    def __str__(self):
        return self.staff_firstname+" - "+self.staff_job_department
    

# ACADEMIC NOTICE FOR ALL CATEGORIES #

class Notice(models.Model):

    category_choice = {
        ('1', 'All'),
        ('2', 'Students'),
        ('3', 'Teachers'),
        ('4', 'Staffs'),
        ('5', 'Students & Teachers'),
        ('6', 'Staffs & Teachers'),
        ('7', 'Administrations'),
    }

    ACTION_CHOICE = {
        ('1', 'Publish'),
        ('0', 'Save as Draft'),
    }

    notice_subject  = models.CharField(max_length=255)
    notice_body     = RichTextField()
    publish_date    = models.DateTimeField(auto_now_add=True)
    publish_category = models.CharField(max_length=20, choices=category_choice, default=1)
    active_status   = models.CharField(max_length=2, choices=ACTION_CHOICE, default=1)


    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.notice_subject

templates/superadmin/academic/addNotice.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} Write a Notice {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
        <!-- Panel Header -->
        <h2 class="ui segment bg-black big block header">
            <img src="{% static '/img/notice.png' %}" alt="" class="ui mini image"> Create Announcement/Notice
        </h2>

        <!-- Main Section -->
        <div class="ui inverted secondary segment">
            <div class="ui attached segments" style="width: 75%; margin: auto;">
                <div class="ui segment bg-black">
                    <h3 class="ui center aligned yellow header">Create a new Announcement</h3>
                </div>
                <div class="ui segment">
                    <form method="POST" class="ui form">
                        <div class="field">
                            <label>Title of Announcement:</label>
                            {{form.notice_subject}}
                        </div>
                        
                        <div class="field">
                            <label>Write Announcement Description:</label>
                            {{form.media}}
                            {{form.notice_body}}
                        </div>

                        <div class="inline field">
                            <label>Category:</label>
                            {{form.publish_category}}
                        </div>
                        <div class="inline field">
                            <label>Action:</label>
                            {{form.active_status}} 
                        </div>
                        <div class="field">
                            {% csrf_token %}
                            <button type="submit" id="publish-button" class="ui green button"><i class="desktop icon"></i>Publish Announcement</button>
                            <button type="submit" class="ui teal button" id="save-to-draft"><i class="save icon"></i>Save to Draf</button>
                            <button href="" id="back" class="ui button"><i class="close icon"></i>Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){
        $('#id_publish_category').dropdown();
        $('#id_active_status').dropdown();
    });
</script>
{% if publish %}
<script>
    $(document).ready(function(){
        $('#id_active_status').css('opacity', '1');
        // $('#publish-button').click(function(){
        //     $('#id_active_status').attr('checked');
        //     $(this).attr('type', 'submit');
        // });
    });
</script>
{% endif %}
{% endblock %}

templates/superadmin/academic/addbook.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} ADD NEW BOOK {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <i class="book icon"></i> [ ___Add-New-Text-Book___ ]
        </h2>
    </div>
    <div class="ui inverted secondary segment" style="height: 90vh;">
        
        <div class="ui segment" style="width: 40%; margin: auto;">
    
            <form method="POST" class="ui form" style="padding: 15px;">
                <h3 class="ui block header">Add New Book</h3>
                <div class="field">
                    <label for="bookname">Book Name</label>
                    {{form.bookname}}
                </div>
                <div class="field">
                    <label for="classfor">Class</label>
                    {{form.classfor}}
                </div>
                <div class="field">
                    <label for="classfor">Subject Code</label>
                    {{form.subjectcode}}
                </div>
                <div class="field">
                    {% csrf_token %}
                    <input type="submit" value="SAVE BOOK INFO" class="ui blue button">
                </div>
            </form>
        </div>

    </div>
</div>
</div>
<script>
    $(document).ready(function(){
       
    });
</script>
{% endblock %}

templates/superadmin/academic/booklist.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} ADMIN DASHBOARD {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <i class="book icon"></i> / Admin Dashboard
        </h2>
    </div>
    <div class="ui segment">
        
        <a href="{% url 'superadmin:addbook' %}" class="ui green button">Add New Book</a>
        <table class="ui inverted celled table">
            <thead>
                <tr>
                    <th>Book Name</th>
                    <th>Class</th>
                    <th>Subject code</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for booklist in list %}
                <tr>
                    <td>{{booklist.bookname}}</td>
                    <td>Class {{booklist.classfor}}</td>
                    <td>Class {{booklist.subjectcode}}</td>
                    <td>
                        <a href="{% url 'superadmin:deletebook' pk=booklist.pk %}" class="ui compact red small button"><i class="trash icon"></i> Delete</a>
                        <a href="{% url 'superadmin:updatebook' pk=booklist.pk %}" class="ui compact teal small button"><i class="edit icon"></i> Update</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
<script>
    $(document).ready(function(){
       
    });
</script>
{% endblock %}

templates/superadmin/academic/delete.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} ADMIN DASHBOARD {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <i class="book icon"></i> Delete Book
        </h2>
    </div>
    <div class="ui segment" style="height: 90vh;">
        
            <div class="ui card" style="width: 35%; margin: auto; background-color:  #ddd; border: 1px solid #666; margin-top: 80px;">
                <div class="content">
                  <div class="header">
                    Delete Confirmation 
                  </div>
                  <div class="ui divider"></div>
                  
                  <div class="description">
                    <form method="post" class="ui center aligned form ">
                        
                        {% csrf_token %}
                        
                    
                    <strong>You are requesting to parmanently delete a data from academic database. Are you confirm to delete?</strong>
                  </div>
                </div>
                <div class="extra content">
                  <div class="ui two buttons">
                    <button type="submit" value="Yes" class="ui green button"><i class="check icon"></i> Yes</button>
                        <button type="button" id="back" class="ui red button"><i class="close icon"></i> No</button>
                </form>
                  </div>
                </div>
              </div>
        </div>

    </div>
</div>
</div>
<script>
    $(document).ready(function(){
       $('#back').click(function(){
        window.history.back();
       });
    });
</script>
{% endblock %}

templates/superadmin/academic/individualnotice.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} {{notice.notice_subject}} {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
        <!-- Panel Header -->
        <h2 class="ui segment bg-black large block header">
            <img src="{% static '/img/notice.png' %}" alt="" class="ui mini image"> Read Individual Notice
        </h2>

        <!-- Main Section -->
        <div class="ui inverted secondary segment" style="padding: 20px 20px; margin: auto;">
            <div class="ui segment" style="width: 75%; margin: auto;">
                <div class="ui segment px-5 py-5" style="padding-bottom: 80px;">
                    <div class="ui inverted segment"></div>
                    <h3>
                        Subject: <a href="" class="ui link">{{notice.notice_subject}}</a>
                    </h3>
                    
                    <span class="meta-text ui label">Published On: {{notice.publish_date}}</span>
                    <div class="ui divider"></div>
                    {{notice.notice_body|safe}}
                    <div class="py-5"></div>
                </div>
                <br>
                {% if notice.active_status == '0' %}
               
                <a href="{% url 'superadmin:updatenotice' pk=notice.pk %}" class="ui teal button"><i class="edit icon"></i>Update</a>
                {% else %}
                <a href="{% url 'superadmin:updatenotice' pk=notice.pk %}" class="ui teal button"><i class="edit icon"></i>Update</a>
                <a href="{% url 'superadmin:deletenotice' pk=notice.pk %}" class="ui red button" id="delete"><i class="trash icon"></i>Delete</a>
                {% endif %}
            </div>
            
            
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){
        
        
    });
</script>
{% endblock %}

templates/superadmin/academic/notices.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} Notice Board | Academy {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
        <!-- Panel Header -->
        <h2 class="ui segment bg-black large block header">
            <img src="{% static '/img/notice.png' %}" alt="" class="ui mini image"> Notice Board 
        </h2>

        <!-- Main Section -->
        


        <div class="ui w-75 segment" style="height: 92vh; margin: auto;">
            <!-- Filter Buttons -->
            <div class="ui buttons">
                <button type="button" class="ui compact button" id="publish-button">
                    <i class="desktop icon"></i>Published
                </button>
                <button type="button" class="ui compact button" id="draft-button">
                    <i class="save icon"></i>Drafts
                </button>
            </div>
            <!-- Published Notice Viewing -->
            <div class="ui segment" id="publishnotice">
                <h3 class="ui block header">Latest Published Notice</h3>
                <div class="ui relaxed divided list">
                    {% for x in published %}
                    <div class="item">
                      <i class="file icon"></i>
                      <div class="content">
                        <a class="header" href="{% url 'superadmin:readnotice' pk=x.pk %}">{{x.notice_subject}}</a>
                        <div class="description">Publish date: {{x.publish_date}}</div>
                      </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
            <!-- Draft Notice Viewing -->
            <div class="ui segment" id="draftnotice">
                <h3 class="ui block header">Draft Notices</h3>
                {% if draft %}
                <div class="ui relaxed divided list">
                    {% for x in draft %}
                    <div class="item">
                      <i class="file icon"></i>
                      <div class="content">
                        <a class="header" href="{% url 'superadmin:readnotice' pk=x.pk %}">{{x.notice_subject}}</a>
                        <div class="description">Publish date: {{x.publish_date}}</div>
                      </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="ui error message">
                    <div class="header"><i>Not draft notice found in server</i></div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){
        $('#draftnotice').hide();
        $('#publish-button').click(function(){
            $('#publishnotice').show();
            $('#draftnotice').hide();
        });
        $('#draft-button').click(function(){
            $('#draftnotice').show();
            $('#publishnotice').hide();
        });
    });
</script>
{% endblock %}

templates/superadmin/academic/update.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} Update Book {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <i class="book icon"></i> / UPDATE BOOK
        </h2>
    </div>
    <div class="ui segment">
        
        <div class="ui segment" style="width: 40%; margin: auto;">
    
            <form method="POST" class="ui form" style="padding: 15px;">
                <h3 class="ui block header">Update Book</h3>
                <div class="field">
                    <label for="bookname">Book Name</label>
                    {{form.bookname}}
                </div>
                <div class="field">
                    <label for="classfor">Class</label>
                    {{form.classfor}}
                </div>
                <div class="field">
                    <label for="classfor">Subject Code</label>
                    {{form.subjectcode}}
                </div>
                <div class="field">
                    {% csrf_token %}
                    <input type="submit" value="UPDATE CHANGES" class="ui blue button">
                </div>
            </form>
        </div>

    </div>
</div>
</div>
<script>
    $(document).ready(function(){
       
    });
</script>
{% endblock %}