sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index, name="indexpage"),
    path('student/', include('studentmanagement.urls')),
    path('teacher/', include('teachermanagement.urls')),
    path('superadmin/', include('superadminmanagement.urls')),
    path('auth/', include('authentications.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentmanagement/urls.py
from django.urls import path 
from . import views


app_name = 'student'

urlpatterns = [
    path('', views.StudentDashboard, name="StDashboard"),
    path('myprofile/', views.StudentProfile, name="StProfile"),
    path('showattendance/', views.StudentShowAttendance, name="StShowAttendance"),
    path('showassignment/', views.StudentAssignment, name="StShowAssignment"),
    path('stpayment/', views.StudentPayment, name="StPayment"),
    path('stnotice/', views.StudentNotice.as_view(), name="StNotice"),
    path('stleave/', views.StudentLeave, name="StLeave"),
    path('printassign/', views.PrintAssignment, name="printassign"),
]

teachermanagement/urls.py
from django.urls import path 
from . import views


app_name = 'teacher'

urlpatterns = [
    path('', views.Index, name="teacherpanel"),
    path('takeattendance/', views.TakeAttendance, name="takeattendance"),
    path('aproveleave/', views.AproveLeave, name="aproveleave"),
    path('assignment/', views.Assignments, name="assignment"),
    path('assignlist/<int:subcode>/<int:st_class>/', views.AssignList, name="assignlist"),
    path('addassignment/<int:sb>/<int:cl>/', views.AddAssignment, name="addassignment"),
    path('deleteassign/<pk>/', views.DeleteAssignment, name="deleteassign"),
    path('assigndetail/<pk>', views.ShowAssignment.as_view(), name="assigndetail"),
]

assignment/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget

# Create your models here.
  
# Book List Model 
class BookList(models.Model):
    CLASS_CHOICES = [
        ('1', 'Class 1'),
        ('2', 'Class 2'),
        ('3', 'Class 3'),
        ('4', 'Class 4'),
        ('5', 'Class 5'),
        ('0', 'Add this book as new book '),
    ]
    bookname = models.CharField(max_length=100)
    classfor = models.CharField(max_length=20, choices=CLASS_CHOICES)
    subjectcode = models.IntegerField()


    def __str__(self):
        return self.bookname


class Assignment(models.Model):
    CLASS_CHOICES = [
        ('1', 'Class 1'),
        ('2', 'Class 2'),
        ('3', 'Class 3'),
        ('4', 'Class 4'),
        ('5', 'Class 5'),
    ]
    stclass = models.CharField(max_length=10, choices=CLASS_CHOICES)
    subject = models.ForeignKey(BookList, on_delete=models.CASCADE, related_name='subjectid')
    assignment = RichTextField()
    publishdate = models.DateTimeField(auto_now_add=True)
    activation = models.CharField(default='1', max_length=1)

    class Meta:
        ordering= ['-publishdate']

    def __str__(self):
        return self.stclass
  

assignment/views.py
from django.shortcuts import render

# Create your views here.

templates/teacher/addassignment.html
{% extends 'teacher/menu.html' %}
{% block title %} Add Assignment {% endblock %}

{% load static %}
{% block body %}

<div class="thirteen wide column">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <img src="{% static '/img/assignment.png' %}" class="ui avatar inline image"> / Add Assignment 
        </h2>
    </div>
    <div class="ui segment">
        {{form.media}}
        <div class="ui raised segment" style="width: 60%; margin: auto;">
            <form class="ui form" method="POST">
                <div class="field">
                    <label for="stclass">Assignment for:</label>
                    {{form.stclass}}
                </div>
                <div class="field">
                    <label for="subject">Subject:</label>
                    {{form.subject}}
                </div>
                <div class="field">
                    {{form.assignment}}
                </div>
                {{form.publishdate}}
                {{form.activation}}
                <div class="field">
                    {% csrf_token %}
                    <input type="submit" value="Submit assignment" class="ui fluid blue button">
                </div>
            </form>
        </div>
    </div>
</div>
</div>


<script>
    $(document).ready(function(){
        $('#id_stclass').addClass('ui selection dropdown');
        $('#id_activation').attr('type', 'hidden');
    });
</script>
{% endblock %}

templates/teacher/aproveleave.html
{% extends 'teacher/menu.html' %}
{% block title %}{{pagetitle}} {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column">
    <div class="ui segments">
        <div class="">
            <h2 class="ui segment bg-black block header">
                <img src="{% static '/img/leave.png' %}" class="ui avatar inline image"> / {{paneltitle}}
            </h2>
        </div>
        <div class="ui segment">
            <div class="ui grid">
                <div class="ten wide column">
                    <div class="ui segment">
                        <h4 class="ui block header">Pending Leave Request</h4>
                        
                        <div class="ui floating info message">
                            <div class="header green">
                              Leave of Advance
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                <span class="meta-text">From - Md Kawsar Alam || Roll no- 125</span><br>
                                <strong>Subject: </strong>
                                <a href="#" class="link" style="text-decoration: underline;">Prayer for leave of advance</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="six wide column">
                    <div class="ui segment">
                        <h4 class="ui block header">Approved Leaves Today</h4>
                        <div class="ui relaxed divided list">
                            <div class="item">
                              <i class="large check circle outline middle aligned icon"></i>
                              <div class="content">
                                <a class="header">Leave of advance</a>
                                <div class="description">Abdullah || Roll No- 125</div>
                              </div>
                            </div>
                            <div class="item">
                              <i class="large check circle outline middle aligned icon"></i>
                              <div class="content">
                                <a class="header">Seek Leave</a>
                                <div class="description">Approve date- 05/03/2024</div>
                              </div>
                            </div>
                            <div class="item">
                              <i class="large check circle outline middle aligned icon"></i>
                              <div class="content">
                                <a class="header">Annual Leave</a>
                                <div class="description">Approve date- 24/04/2024</div>
                              </div>
                            </div>
                            
                          </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/teacher/assignlist.html
{% extends 'teacher/menu.html' %}
{% block title %} Assignment List {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <img src="{% static '/img/dashboard.png' %}" class="ui avatar inline image"> / Assignment List for  
        </h2>
    </div>
    <div class="ui segment">
        
        <a href="{% url 'teacher:addassignment' sb=subject cl=class %}" class="ui blue button">Add Assignment</a>
        <div class="ui divider"></div>
        {% if assign %}
        <div class="ui segment">
            <!-- <div class="ui two column grid">
                <div class="column"> -->

                    {% for ass in assign %}
                    <!-- Assignment Box -->
                    <div class="ui attached info message segment inline"  style="width: 48%;">
                        <div class="header">
                            <strong>Subject- </strong>{{ass.subject}}
                        </div>
                      </div>
                      <div class="ui attached fluid segment" style="width: 48%;">
                        <small class="ui compact label">Date: {{ass.publishdate}}</small>
                        <br>
                        {{ass.assignment|safe}}
                      </div>
                      <div class="ui bottom attached info message" style="width: 48%;">
                        <i class="icon help"></i>
                        After completing assignment, Click <a href="{% url 'teacher:deleteassign' pk=ass.pk  %}" class="ui compact teal button"><i class="check icon"></i> Complete</a>
                      </div>

                    {% endfor %}
                <!-- </div>
            </div> -->
        </div>
        {% else %}
        <strong>No assignment found for this subject</strong>
        {% endif %}
    </div>
</div>
</div>

{% endblock %}

templates/teacher/assignment.html
{% extends 'teacher/menu.html' %}
{% block title %}{{pagetitle}} {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column">
    <div class="ui segments">
        <div class="">
            <h2 class="ui segment bg-black block header">
                <img src="{% static '/img/assignment.png' %}" class="ui avatar inline image"> / {{paneltitle}}
            </h2>
        </div>
        <div class="ui segment">
            <div class="ui styled fluid accordion">
                <div class="title">
                  <i class="dropdown icon"></i>
                  Assignment for Class 1
                </div>
                <div class="content">
                  <div class="ui two column grid">
                    <div class="column">
                        <div class="ui floating info message">
                            <div class="ui middle aligned divided list">
                              {% for book in class_one %}
                                <a href="{% url 'teacher:assignlist' subcode=book.id st_class=book.classfor %}" class="item">
                                    <div class="ui small header">{{book.bookname}}</div>
                                </a>
                              {% endfor %}
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                 
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        
                    </div>
                  </div>
                </div>
                <div class="title">
                  <i class="dropdown icon"></i>
                  Assignment for Class 2
                </div>
                <div class="content">
                  <div class="ui two column grid">
                    <div class="column">
                        <div class="ui floating info message">
                            <div class="ui middle aligned divided list">
                              {% for book in class_two %}
                                <a href="{% url 'teacher:assignlist' subcode=book.id st_class=book.classfor %}" class="item">
                                    <div class="ui small header">{{book.bookname}}</div>
                                </a>
                              {% endfor %}
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                 
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        
                    </div>
                  </div>
                </div>
                <div class="title ">
                  <i class="dropdown icon"></i>
                  Assignment for Class 3
                </div>
                <div class="content ">
                  <div class="ui two column grid">
                    <div class="column">
                        <div class="ui floating info message">
                            <div class="ui middle aligned divided list">
                              {% for book in class_three %}
                                <a href="{% url 'teacher:assignlist' subcode=book.id st_class=book.classfor %}" class="item">
                                    <div class="ui small header">{{book.bookname}}</div>
                                </a>
                              {% endfor %}
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                 
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        
                    </div>
                  </div>
                </div>

                
                <div class="title ">
                  <i class="dropdown icon"></i>
                  Assignment for Class 4
                </div>
                <div class="content ">
                  <div class="ui two column grid">
                    <div class="column">
                        <div class="ui floating info message">
                            <div class="ui middle aligned divided list">
                              {% for book in class_four %}
                                <a href="{% url 'teacher:assignlist' subcode=book.id st_class=book.classfor %}" class="item">
                                    <div class="ui small header">{{book.bookname}}</div>
                                </a>
                              {% endfor %}
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                 
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        
                    </div>
                  </div>
                </div>

                <div class="title ">
                  <i class="dropdown icon"></i>
                  Assignment for Class 5
                </div>
                <div class="content ">
                  <div class="ui two column grid">
                    <div class="column">
                        <div class="ui floating info message">
                            <div class="ui middle aligned divided list">
                              {% for book in class_five %}
                                <a href="{% url 'teacher:assignlist' subcode=book.id st_class=book.classfor %}" class="item">
                                    <div class="ui small header">{{book.bookname}}</div>
                                </a>
                              {% endfor %}
                            </div>
                            <div class="ui divider"></div>
                            <p>
                                 
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        
                    </div>
                  </div>
                </div>


              </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
       $('.ui.accordion').accordion();
    });
</script>
{% endblock %}

templates/teacher/deleteassignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css" integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Delete/Complete Section</title>
</head>
<body style="background-color: #666; padding: 120px 0px;">
    <div class="ui attached info segments" style="width: 400px; margin: auto; margin-top: 30px !important;">
        <div class="ui segment"><strong>Confirmation</strong></div>
        <div class="ui segment">
            Are you sure you want to complete this assignment for this particular Class?
        </div>
        <div class="ui raised segment">
            <form method="POST" class="ui form">
                <div>
                    
                    <div class="ui modal">
                        <div class="header">Header</div>
                        <div class="content">
                            {{form.media}}
                            {{form}}
                        </div>
                      </div>
                </div>
                {% csrf_token %}
                <input type="submit" value="Confirm" class="ui blue button">
                <a href="{% url 'teacher:assignlist' subcode=subject.id st_class=stclass %}" class="ui secondary button">Cancel</a>
            </form>
        </div>
        </div>
        
    </div>

    <script>
        $(document).ready(function(){
        });
    </script>
</body>
</html>

templates/teacher/index.html
{% extends 'teacher/menu.html' %}
{% block title %}{{pagetitle}} {% endblock %}
{% load static %}
{% block body %}
<div class="thirteen wide column">
    <h2 class="ui inverted large segment">
        <img src="{% static '/img/dashboard.png' %}" class="ui avatar inline image"> / {{paneltitle}}
    </h2>
    <div class="div ui segment">
        <div class="ui four column centered grid">
            <div class="column centered">
                <a href="{% url 'teacher:takeattendance' %}">
                <div class="panel gradient-red">
                    <h4 class="ui yellow header">Take Attendance</h4>
                    <div class="ui divider"></div>
                    <span class="cirular">01</span>
                </div>
                </a>
            </div>
            <div class="column centered">
                <a href="{% url 'teacher:aproveleave' %}">
                <div class="panel gradient-blue">
                    <h4 class="ui yellow header">Leave Aproval</h4>
                    <div class="ui divider"></div>
                    <span class="cirular">02</span>
                </div>
                </a>
            </div>
            <div class="column">
                <a href="{% url 'teacher:assignment' %}">
                <div class="panel gradient-green">
                    <h4 class="ui yellow header">Assignment Implement</h4>
                    <div class="ui divider"></div>
                    <span class="cirular">03</span>
                </div>
                </a>
            </div>
            <div class="column">
                <a href="{% url 'student:StPayment' %}">
                <div class="panel gradient-pink">
                    <h4 class="ui yellow header">Announce Notice</h4>
                    <div class="ui divider"></div>
                    <span class="cirular">04</span>
                </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/teacher/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css" integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js" integrity="sha512-Xo0Jh8MsOn72LGV8kU5LsclG7SUzJsWGhXbWcYs2MAmChkQzwiW/yTQwdJ8w6UA9C6EVG18GHb/TrYpYCjyAQw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <title>{% block title %} {% endblock %}</title>
    
</head>
<body>
    <div class="ui grid">
        <div class="three wide column">
            <div class="fixed-vertical-menu">
                <div class="ui vertical inverted large menu">
                    <div class="center aligned huge item">
                        <img src="{% static '/img/profile.png' %}" class="ui tiny circular image centered">
                        <p class="ui center aligned grey large header">Teacher Name</p>
                    </div>
                    <a href="{% url 'teacher:teacherpanel' %}" class="item {% if active_th_dashboard %} active {% endif %}">
                        Dashboard
                    </a>
                    <a href="{% url 'teacher:assignment' %}" class="item {% if active_th_assignment %} active {% endif %}">
                        Assignments
                    </a>
                    <a href="{% url 'teacher:takeattendance' %}" class="item {% if active_th_attendance %} active {% endif %}">
                        Attendance
                    </a>
                    <a href="{% url 'teacher:aproveleave' %}" class="item {% if active_th_leave %} active {% endif %}">
                        Leave of Absent
                    </a>
                    <a href="" class="item {% if active_th_notice %} active {% endif %}">
                        Notice/Announcement
                    </a>
                    <a href="" class="item {% if active_th_payment %} active {% endif %}">
                        Payment option
                    </a>
                    <br><br>
                    <div class="ui vertical animated secondary button" tabindex="0">
                        <div class="visible content"><i class="user large icon"></i></div>
                        <div class="hidden content">
                          Profile
                        </div>
                    </div>
                    
                    <div class="ui vertical animated secondary button" tabindex="0">
                        <div class="visible content"><i class="lock icon large"></i></div>
                        <div class="hidden content">
                          Password
                        </div>
                    </div>
                    <a class="ui vertical animated secondary button" tabindex="0" href="{% url 'indexpage' %}">
                        <div class="visible content"><i class="power off large icon"></i></div>
                        <div class="hidden content">
                          Logout
                        </div>
                    </a>
                </div>
            </div>
        </div>

    {% block body %}

    {% endblock %}
</div>
</div>
</div>
<script src="{% static '/js/main.js' %}"></script>
</body>
</html>

templates/teacher/takeattendance.html
{% extends 'teacher/menu.html' %}
{% block title %}{{pagetitle}} {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment bg-black block header">
            <img src="{% static '/img/dashboard.png' %}" class="ui avatar inline image"> / {{paneltitle}}
        </h2>
    </div>
    <div class="ui segment">
        <form action="" class="ui form small">
            <div class="ui grid">
                <div class="three wide column">
                    <div class="field">
                        <label for="">Date</label>
                        <input type="date" name="date" required>
                    </div>
                </div>
                <div class="three wide column">
                    <div class="field">
                        <label for="class">Class: </label>
                        <select name="class" id="class" class="ui selection dropdown" required> 
                            <option value="">Select class...</option>
                            <option value="1">Class 1</option>
                            <option value="2">Class 2</option>
                            <option value="3">Class 3</option>
                            <option value="4">Class 4</option>
                            <option value="5">Class 5</option>
                        </select>
                    </div>
                </div>
                <div class="ten wide column">
                    <div class="field">
                        <label for="">&nbsp;</label>
                        <button type="button" class="ui teal button" id="attendance-button">Take attendance</button>
                    </div>
                </div>
            </div>
        </form>
        <div class="ui raised segment">
            <table class="ui celled selectable compact table">
                <thead>
                    <tr class="ui inverted black table">
                        <th>Roll</th>
                        <th>Name</th>
                        <th>Attendance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>01</td>
                        <td>Md Kawsar Alam</td>
                        <td>
                            <div class="ui form">
                                <div class="inline field px">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="st2024001" tabindex="0" class="hidden">
                                        <label>Present</label>
                                    </div>
                                    <div class="ui radio checkbox" style="margin-right: 10px;">
                                        <input type="radio" name="st2024001" tabindex="0" class="hidden">
                                        <label>Absent</label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>02</td>
                        <td>Masud Alam</td>
                        <td>
                            <div class="ui form">
                                <div class="inline field px">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="st2024002" tabindex="0" class="hidden">
                                        <label>Present</label>
                                    </div>
                                    <div class="ui radio checkbox" style="margin-right: 10px;">
                                        <input type="radio" name="st2024002" tabindex="1" class="hidden">
                                        <label>Absent</label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>03</td>
                        <td>Saiful Azam Babar</td>
                        <td>
                            <div class="ui form">
                                <div class="inline field px">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="st2024002" tabindex="0" class="hidden">
                                        <label>Present</label>
                                    </div>
                                    <div class="ui radio checkbox" style="margin-right: 10px;">
                                        <input type="radio" name="st2024002" tabindex="1" class="hidden">
                                        <label>Absent</label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>04</td>
                        <td>Morshed Khan</td>
                        <td>
                            <div class="ui form">
                                <div class="inline field px">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="st2024002" tabindex="0" class="hidden">
                                        <label>Present</label>
                                    </div>
                                    <div class="ui radio checkbox" style="margin-right: 10px;">
                                        <input type="radio" name="st2024002" tabindex="1" class="hidden">
                                        <label>Absent</label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>05</td>
                        <td>Abdullah</td>
                        <td>
                            <div class="ui form">
                                <div class="inline field px">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="st2024002" tabindex="0" class="hidden">
                                        <label>Present</label>
                                    </div>
                                    <div class="ui radio checkbox" style="margin-right: 10px;">
                                        <input type="radio" name="st2024002" tabindex="1" class="hidden">
                                        <label>Absent</label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    
</div>
</div>



{% endblock %}