sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index, name="indexpage"),
    path('student/', include('studentmanagement.urls')),
    path('teacher/', include('teachermanagement.urls')),
    path('superadmin/', include('superadminmanagement.urls')),
    path('auth/', include('authentications.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superadminmanagement/urls.py
from django.urls import path 
from . import views


app_name = 'superadmin'

urlpatterns = [
    path('', views.Dashboard, name="admindashboard"),
    path('booklist/', views.Booklist.as_view(), name="booklist"),
    path('addbook/', views.AddBook.as_view(), name="addbook"),
    path('<pk>/updatebook', views.UpdateBook.as_view(), name="updatebook"),
    path('<pk>/delete/', views.DeleteBook.as_view(), name="deletebook"),
    path('addstudent/', views.AddStudent.as_view(), name="addstudent"),
    path('students/', views.AllStudent.as_view(), name="allstudent"),
    path('studentdetail/<pk>', views.StudentDetail.as_view(), name="studentdetail"),
    path('createnotice/', views.CreateNotice.as_view(), name="createnotice"),
    path('noticelist/', views.ListNotice, name="noticelist"),
    path('readnotice/<pk>', views.ReadNotice.as_view(), name="readnotice"),
    path('updatenotice/<pk>', views.UpdateNotice.as_view(), name="updatenotice"),
    path('deletenotice/<pk>', views.DeleteNotice.as_view(), name="deletenotice"),
]

templates/superadmin/dashboard.html
{% extends 'superadmin/menu.html' %}
{% block title %}{{pagetitle}} ADMIN DASHBOARD {% endblock %}
{% load static %}
{% block body %}

<div class="thirteen wide column" style="z-index: 99;">
    <div class="ui segments">
    <div class="">
        <h2 class="ui segment large bg-black block header">
            <img src="{% static '/img/dashboard.png' %}" alt="" class="ui mini image"> Super Admin Dashboard
        </h2>
    </div>
    <div class="ui segment">
        
        <div class="ui four column centered grid">
            <div class="column centered">
                <a href="{% url 'superadmin:allstudent' %}">
                <div class="panel gradient-red">
                    <h4 class="ui white-text large text-white header">Total Students</h4>
                    <!-- <div class="ui divider"></div> -->
                    <span class="ui circular big label">{{totalstudent}}</span>
                </div>
                </a>
            </div>
            <div class="column centered">
                <a href="#">
                <div class="panel gradient-blue">
                    <h4 class="ui large header text-white">Total Teachers</h4>
                    <!-- <div class="ui divider"></div> -->
                    <span class="ui circular big label">{{totalteacher}}</span>
                </div>
                </a>
            </div>
            <div class="column">
                <a href="#">
                <div class="panel gradient-green">
                    <h4 class="ui large header text-white">Total Staffs</h4>
                    <!-- <div class="ui divider"></div> -->
                    <span class="ui circular big label">{{totalstaff}}</span>
                </div>
                </a>
            </div>
            <div class="column">
                <a href="#">
                <div class="panel gradient-pink">
                    <h4 class="ui large header text-white">Total Students</h4>
                    <!-- <div class="ui divider"></div> -->
                    <span class="ui circular big label">{{totalstudent}}</span>
                </div>
                </a>
            </div>
        </div>
        <div class="ui centered header"> 
            <img src="{% static '/img/logo.png' %}" alt="" style="width: 700px;">
        </div>
    </div>
</div>
</div>
<script>
    $(document).ready(function(){
       
    });
</script>
{% endblock %}

templates/superadmin/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css" integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js" integrity="sha512-Xo0Jh8MsOn72LGV8kU5LsclG7SUzJsWGhXbWcYs2MAmChkQzwiW/yTQwdJ8w6UA9C6EVG18GHb/TrYpYCjyAQw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <title>{% block title %} {% endblock %}</title>
    
</head>
<body>
    <div class="ui grid">
        <div class="three wide column">
            <div class="fixed-vertical-menu">
                <div class="ui vertical inverted large menu">
                    <div class="center aligned huge item">
                        <img src="{% static '/img/profile.png' %}" class="ui tiny circular image centered">
                        <p class="ui center aligned grey large header">Super Admin</p>
                    </div>
                    <a href="{% url 'superadmin:admindashboard' %}" class="item ">
                        Dashboard
                    </a>
                    <div class="ui inverted dropdown item">
                        Academy
                        <i class="dropdown icon"></i>
                        <div class="menu sub-menu">
                          <a class="item" href="{% url 'superadmin:addbook' %}">
                            <i class="add user icon"></i> Add Book
                          </a>
                          <a class="item" href="{% url 'superadmin:booklist' %}">
                            <i class="list alternate outline icon"></i> Book List
                          </a>
                          <a class="item">
                            <i class="wrench icon"></i> Settings
                          </a>
                        </div>
                    </div>
                    <div class="ui inverted dropdown item">
                        Student
                        <i class="dropdown icon"></i>
                        <div class="menu sub-menu">
                          <a class="item" href="{% url 'superadmin:addstudent' %}">
                            <i class="add user icon"></i> Add New Student
                          </a>
                          <a class="item" href="{% url 'superadmin:allstudent' %}">
                            <i class="list alternate outline icon"></i> All Student
                          </a>
                        </div>
                    </div>

                    <div class="ui inverted dropdown item">
                    Teacher
                    <i class="dropdown icon"></i>
                    <div class="menu sub-menu">
                        <a class="item">
                        <i class="add user icon"></i> Add Teacher
                        </a>
                        <a class="item">
                        <i class="list alternate outline icon"></i> All Teacher
                        </a>
                    </div>
                    </div>
                    
                    <div class="ui inverted dropdown item">
                    Staff
                    <i class="dropdown icon"></i>
                    <div class="menu sub-menu">
                        <a class="item">
                        <i class="add user icon"></i> Add New Staff
                        </a>
                        <a class="item">
                        <i class="list alternate outline icon"></i> All Staff List
                        </a>
                    </div>
                    </div>
                    <div class="ui inverted dropdown item">
                      Notice / Announcement
                      <i class="dropdown icon"></i>
                      <div class="menu sub-menu">
                          <a class="item" href="{% url 'superadmin:createnotice' %}">
                          <i class="add user icon"></i> Write a notice
                          </a>
                          <a class="item" href="{% url 'superadmin:noticelist' %}">
                          <i class="list alternate outline icon"></i> Published Notices
                          </a>
                          <a class="item">
                          <i class="list alternate outline icon"></i> Draft Notices
                          </a>
                      </div>
                    </div>
                    <a href="#" class="item ">
                        Salary Management
                    </a>
                    
                    <a href="#" class="item ">
                        Payment option
                    </a>
                    <br><br>
                    <div class="ui vertical animated secondary button" tabindex="0">
                        <div class="visible content"><i class="user large icon"></i></div>
                        <div class="hidden content">
                          Profile
                        </div>
                    </div>
                    
                    <div class="ui vertical animated secondary button" tabindex="0">
                        <div class="visible content"><i class="lock icon large"></i></div>
                        <div class="hidden content">
                          Password
                        </div>
                    </div>
                    <a class="ui vertical animated secondary button" tabindex="0" href="{% url 'indexpage' %}">
                        <div class="visible content"><i class="power off large icon"></i></div>
                        <div class="hidden content">
                          Logout
                        </div>
                    </a>
                </div>
            </div>
        </div>

    {% block body %}

    {% endblock %}
</div>
</div>
</div>
<script src="{% static '/js/main.js' %}"></script>
</body>
</html>